theme: minima

title: Portfolio
author: João Azevedo
description: Powered by GitHub Pages

avatar: "https://avatars.githubusercontent.com/u/8609196"
round-avatar: true

social-network-links:
  github: 9joao6
  twitter: 9joao6
  youtube: "@9joao6"
  linkedin: joão-azevedo-b394272a9
  bluesky: 9joao6
  itchio: 9joao6
share-links-active:
  github: true
  twitter: true
  youtube: true
  linkedin: true
  bluesky: true
  itchio: true
